blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/material-theme/vsc-material-theme-icons/discussions
    about: If you have questions or different type of requests, use the Discussions page.
